<?php

namespace Bpi\Sdk\Tests\Unit;

use GuzzleHttp\ClientInterface as HttpClientInterface;

/**
 * Class Bpi
 *
 * Wrapper around \Bpi that allows injecting the client used for requests.
 *
 * @package Bpi\Sdk\Tests\Unit
 */
class BpiClient extends \Bpi {
    private $injectedClient;

    public function __construct($endpoint, $agencyId = null, $publicKey = null, $secret = null)
    {
        if ($endpoint instanceof HttpClientInterface) {
            $this->injectedClient = $endpoint;
        } else {
            parent::__construct($endpoint, $agencyId, $publicKey, $secret);
        }
    }

    protected function request($method, $url, array $data = [])
    {
        if ($this->injectedClient !== null) {
            return $this->injectedClient->request($method, $url, $data);
        }

        return parent::request($method, $url, $data); // TODO: Change the autogenerated stub
    }
}
